### ISSUE TITLE
[DECK.GL] Demo avec GeoJsonLayer

### ISSUE THREAD

**Issue by zacun** [VCityTeam/TIW5-3DUrbanDataVizualization#2]
Créer une démo utilisant la librairie `deck.gl` et les layers de type : `GeoJsonLayer`
- deck.gl : https://deck.gl/examples
- Jeu de données : https://data.grandlyon.com/jeux-de-donnees/centres-medico-psychologiques-metropole-lyon/telechargements
- Type de projection : EPSG:4326 (https://epsg.io/4326)

**Comment by abdenourbarache** [comment]
![image](https://user-images.githubusercontent.com/53235522/143090668-5eb1b271-21fe-4ce9-92f2-c06335a4348a.png)
