### ISSUE TITLE
[UD-Viz]  Demo avec le quartier Lyon 1er

### ISSUE THREAD

**Issue by zacun** [VCityTeam/TIW5-3DUrbanDataVizualization#4]
Demo avec le quartier Lyon 1er
- Faire en sorte que l'extend (la surface 2D avec l'image satellite) corresponde bien à la surface du quartier

**Comment by MohamedRAJI** [comment]
**assets/config/config.json**
```
  "3DTilesLayers": [
    {
      "id": "Lyon-1",
      "url": "https://dataset-dl.liris.cnrs.fr/three-d-tiles-lyon-metropolis/2015/Lyon-1_2015/tileset.json",
      "color": "0xFFFFFF"
    }
  ],
  "extents": {
    "min_x": "1841077.72",
    "max_x": "1842954.03",
    "min_y": "5175477.47",
    "max_y": "5176611.44"
  },
```

**Comment by MohamedRAJI** [comment]
**Lyon 1** 
![image](https://user-images.githubusercontent.com/76049119/143067744-9afe0c80-816a-4b34-bf86-48cfeec1ed4e.png)
