### ISSUE TITLE
[UD-Viz] Démo avec les quartiers Lyon 2eme et Lyon 3eme

### ISSUE THREAD

**Issue by zacun** [VCityTeam/TIW5-3DUrbanDataVizualization#5]
Demo avec les quartiers Lyon 2 et Lyon 3
- Faire en sorte que l'extend (la surface 2D avec l'image satellite) corresponde bien à la surface du quartier

**Comment by AnassMouhyDine** [comment]
Lyon 2eme:

![Lyon2](https://user-images.githubusercontent.com/93133646/143051204-b02a89f4-c220-4888-bb87-d035cb212107.png)

Lyon 3eme:

![Lyon3](https://user-images.githubusercontent.com/93133646/143051312-281a41dc-6377-4789-9d4c-bf5ceee782d8.png)

 Lyon 2eme et 3eme:

![Demo_Lyon2_3](https://user-images.githubusercontent.com/93133646/143051384-08f3e331-8637-4d5d-a042-cdc5d1cdf820.png)
